apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: secretcont
    image: nginx
    env:
    - name: secretenv
      valueFrom:
        secretKeyRef:
          name: secretdemo
          key: myKey
