apiVersion: v1
kind: Pod
metadata:
  name: resreq
spec:
  containers:
  - name: resreq
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "70Mi"
        cpu: "300m"

